# Generated by Django 4.1.6 on 2023-05-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(max_length=150)),
                ('fecha', models.CharField(max_length=150)),
                ('escudoCasa', models.CharField(max_length=150)),
                ('escudoVisitante', models.CharField(max_length=150)),
                ('equipoCasa', models.CharField(max_length=150)),
                ('equipoVisitante', models.CharField(max_length=150)),
                ('hora', models.CharField(max_length=150)),
                ('resultadoCasa', models.CharField(max_length=150)),
                ('resultadoVisitante', models.CharField(max_length=150)),
                ('estadoPartido', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEquipo', models.CharField(max_length=150)),
                ('points', models.CharField(max_length=150)),
                ('partidosJugador', models.CharField(max_length=150)),
                ('partidosGanados', models.CharField(max_length=150)),
                ('partidosEmpatados', models.CharField(max_length=150)),
                ('partidosPerdidos', models.CharField(max_length=150)),
                ('golesFavor', models.CharField(max_length=150)),
                ('golesContra', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEquipo', models.CharField(max_length=150)),
                ('photoEscudo', models.CharField(max_length=150)),
                ('photoEstadio', models.CharField(max_length=150)),
                ('estadio', models.CharField(max_length=150)),
                ('anoFundacion', models.CharField(max_length=150)),
                ('entrenador', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=150)),
                ('tokenSession', models.CharField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJugadora', models.CharField(max_length=150)),
                ('photoJugadora', models.CharField(max_length=150)),
                ('numeroJugadora', models.CharField(max_length=150)),
                ('idEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.equipos')),
            ],
        ),
    ]
