# Generated by Django 4.1.6 on 2023-05-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadoras',
            name='posicionJugadora',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
